### ISSUE TITLE
Pip install fails on OSX: "python.cc:3:10: fatal error: 'unordered_map' file not found"

### ISSUE THREAD

**Issue by buhrmann** [src-d/wmd-relax#5]
pip install git+https://github.com/src-d/wmd-relax fails on OS X (python 3), with following message:

```
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/thomas/anaconda/envs/fasttext/include -arch x86_64 -I/Users/thomas/anaconda/envs/fasttext/include -arch x86_64 -I/Users/thomas/anaconda/envs/fasttext/lib/python3.6/site-packages/numpy/core/include -Ior-tools/src -I/Users/thomas/anaconda/envs/fasttext/include/python3.6m -c python.cc -o build/temp.macosx-10.7-x86_64-3.6/python.o -std=c++11 -march=native -ftree-vectorize -DNDEBUG -Wno-sign-compare -flto
    python.cc:3:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1
```

Since the install refers to unordered_map it would seem the compiler might need to know about libc++ (including the flag -stdlib=libc++) perhaps?

**Comment by vmarkovtsev** [comment]
Are you using macOS 10.7? Unordered map is the part of the standard library in C++11. Your compiler is either very old or screwed, what's the version?  That being said, I have not tested wmd-relax on macOS yet.

**Comment by vmarkovtsev** [comment]
`pip3 install git+https://github.com/src-d/wmd-relax` works for me on macOS. It takes a while, several minutes since it clones or-tools. sdist is broken at the moment.

**Comment by vmarkovtsev** [comment]
Fixed by e52af6a2b35c0010ae74e3a9f1be120bc061c66f

**Comment by memray** [comment]
Same problem. Cannot solve yet

**Comment by thisislance98** [comment]
I'm getting the same problem

**Comment by vmarkovtsev** [comment]
Can you please elaborate? It is currently working in Travis macOS and I tested it in 4 different macOS setups. Error message? If it is in Anaconda/alike - it is not supported.

**Comment by memray** [comment]
Hmm, yes, it's anaconda environment. So what if I use the built-in python?

**Comment by vmarkovtsev** [comment]
Pip installation is tested and works. Does it work for you?

**Comment by jmague** [comment]
I ran into the same problem with an anaconda environment. I kind of solved it by installing the package with the default pip (/usr/local/bin/pip3) and then moving the wmd files from the default python site-pakages directory to the anaconda python site-packages directory:
```bash
cp -r /usr/local/lib/python3.6/site-packages/*wmd* /opt/anaconda/lib/python3.6/site-packages
```
I'm pretty sure it's not a good practice, but it worked...

**Comment by aloosley** [comment]
Same problem with `pip` using Anaconda  4.3.30, OSX 10.13.3.

I haven't yet found a solution.

**Comment by vmarkovtsev** [comment]
I need the full configuration and build logs `VERBOSE=1 make`. MacOS seems to be my pain.

**Comment by aloosley** [comment]
```
Collecting wmd
  1 location(s) to search for versions of wmd:
  * https://pypi.python.org/simple/wmd/
  Getting page https://pypi.python.org/simple/wmd/
  Looking up "https://pypi.python.org/simple/wmd/" in the cache
  Current age based on date: 330
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 330
  Analyzing links from page https://pypi.python.org/simple/wmd/
    Skipping link https://pypi.python.org/packages/12/23/b1aacc95e4b9685e4d00829137e2d9a8eac3d6d7006a9e15866d5c1da109/wmd-1.2.6-cp35-cp35m-manylinux1_x86_64.whl#md5=0d47c9fdd7d8b0f4cd70fa99d737688d (from https://pypi.python.org/simple/wmd/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/30/18/abbc5887550fd7e263717895882a6b387354a796258e1fa98ad8250e7b22/wmd-1.2.3-cp35-cp35m-manylinux1_x86_64.whl#md5=976449ccb3f23b9a52ade5687f28abd0 (from https://pypi.python.org/simple/wmd/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/30/2e/66f1c9b8ae71ed43fca6cfc5caba7b9604dd66e94d4d18c996401c69ce3b/wmd-1.2.1-cp35-cp35m-manylinux1_x86_64.whl#md5=cb5a42b0f6e301c50b1a0740384f6cc3 (from https://pypi.python.org/simple/wmd/); it is not compatible with this Python
    Skipping link https://pypi.python.org/packages/42/e5/9c8a3fe67f298712b4830431426dea2d248421db5fddf13c573e6384f2df/wmd-1.2.4-cp35-cp35m-manylinux1_x86_64.whl#md5=093bdbfea480498094bb901c4ecf2f72 (from https://pypi.python.org/simple/wmd/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/4a/38/4a7b32c593bbbc073f2ca86c509a0cb8e931bd85d7c4475f5a06698429f3/wmd-1.2.3.tar.gz#md5=bd4ed7650378a611a420c9fe652c4515 (from https://pypi.python.org/simple/wmd/), version: 1.2.3
    Skipping link https://pypi.python.org/packages/5f/f4/67cbf24a848a57e15c0e9ad686f9aa5bab07124ff93b57e6fdb519f1331e/wmd-1.2.2-cp35-cp35m-manylinux1_x86_64.whl#md5=1f7c56b1aab0c3a9e3ebcace9bbde0b1 (from https://pypi.python.org/simple/wmd/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/62/14/f7b811c3db1cb53382c3a4b31129b49f5b0d92cc0f9570b4f4183843ebc7/wmd-1.2.7.tar.gz#md5=552a7d86511d90adc79da9f5c02ef57c (from https://pypi.python.org/simple/wmd/), version: 1.2.7
    Found link https://pypi.python.org/packages/66/8b/aa69c2254bf1a0f5f1193f16598ef7f1dadc10eefb9d657c7d1a1bad6cf8/wmd-1.2.5.tar.gz#md5=53e06d87d4adc31504c1d1335290cc3a (from https://pypi.python.org/simple/wmd/), version: 1.2.5
    Skipping link https://pypi.python.org/packages/66/ad/d5f0a11c62a9eee45f2a984a198681148df4630440d67661335c3420d1e3/wmd-1.2.5-cp35-cp35m-manylinux1_x86_64.whl#md5=3dd6bdeefeec027c3746094a059866de (from https://pypi.python.org/simple/wmd/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/76/13/a9dba97e97d3e357d3f5e2358a70974c20cfbf03c013ec11765025c48fa1/wmd-1.2.2.tar.gz#md5=2ecb9da872d3451dee787f25aa5ca3a4 (from https://pypi.python.org/simple/wmd/), version: 1.2.2
    Skipping link https://pypi.python.org/packages/a4/0e/99fae33fdd8263110b02bb709e91b6564d51feac9e14cc8aa1d591269768/wmd-1.1.6-cp35-cp35m-manylinux1_x86_64.whl#md5=449415f24dae5a8ac6b45adfac3891a2 (from https://pypi.python.org/simple/wmd/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/ac/b9/135ef0bc41052e84fe0d54e1be25f37348364b67249a18278185436e1d6a/wmd-1.1.6.tar.gz#md5=fee6235f07d40cfbd834fcb338840a7b (from https://pypi.python.org/simple/wmd/), version: 1.1.6
    Skipping link https://pypi.python.org/packages/c9/18/b996ddee76ef913ab396deea78eeb855d290990855ed99d6baa438f3a2e0/wmd-1.2.0-cp35-cp35m-manylinux1_x86_64.whl#md5=7d3112419275f25164f7ab5f0ec07a96 (from https://pypi.python.org/simple/wmd/); it is not compatible with this Python
    Found link https://pypi.python.org/packages/d3/74/3f52c3d9617f985ef9930bade13e384fb1566f87377dd34175dea87d0318/wmd-1.2.4.tar.gz#md5=0e89ad4013544c8de2f1324d167d17fe (from https://pypi.python.org/simple/wmd/), version: 1.2.4
    Found link https://pypi.python.org/packages/d9/e1/70748531fbdd165272a98b2462bf0d893c552933ed011cc3d16acf246bfb/wmd-1.2.1.tar.gz#md5=a0a5e3aeaf67c18fee61a8628d306494 (from https://pypi.python.org/simple/wmd/), version: 1.2.1
    Found link https://pypi.python.org/packages/f0/5d/50b61af8e4f40f188518ce08bef3f627239a4bc4723d85ddf8a4a1748083/wmd-1.2.6.tar.gz#md5=d7d894d5ad6d3ef8ac1989723c02a9b4 (from https://pypi.python.org/simple/wmd/), version: 1.2.6
    Found link https://pypi.python.org/packages/f8/ba/de2bd144e82e3a2696146fda64de678d8fa247f39b28bff64f06ca3edbad/wmd-1.2.0.tar.gz#md5=fd20d412853d80a2cd4e834d91a8c470 (from https://pypi.python.org/simple/wmd/), version: 1.2.0
    Found link https://pypi.python.org/packages/fe/a1/84d228ca438f1bd5b707045571da9d72bab54c75a87a0585675f4ef5b866/wmd-1.2.8.tar.gz#md5=de5793504f99fcf640884203d685cd8c (from https://pypi.python.org/simple/wmd/), version: 1.2.8
  Using version 1.2.8 (newest of versions: 1.1.6, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8)
  Looking up "https://pypi.python.org/packages/fe/a1/84d228ca438f1bd5b707045571da9d72bab54c75a87a0585675f4ef5b866/wmd-1.2.8.tar.gz" in the cache
  Current age based on date: 12970
  Freshness lifetime from max-age: 31557600
  The response is "fresh", returning cached response
  31557600 > 12970
  Using cached wmd-1.2.8.tar.gz
  Downloading from URL https://pypi.python.org/packages/fe/a1/84d228ca438f1bd5b707045571da9d72bab54c75a87a0585675f4ef5b866/wmd-1.2.8.tar.gz#md5=de5793504f99fcf640884203d685cd8c (from https://pypi.python.org/simple/wmd/)
  Running setup.py (path:/private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd/setup.py) egg_info for package wmd
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/wmd.egg-info
    writing pip-egg-info/wmd.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/wmd.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/wmd.egg-info/requires.txt
    writing top-level names to pip-egg-info/wmd.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/wmd.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/wmd.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/wmd.egg-info/SOURCES.txt'
  Source in /private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd has version 1.2.8, which satisfies requirement wmd from https://pypi.python.org/packages/fe/a1/84d228ca438f1bd5b707045571da9d72bab54c75a87a0585675f4ef5b866/wmd-1.2.8.tar.gz#md5=de5793504f99fcf640884203d685cd8c
Requirement already satisfied: numpy in /Users/aloosley/anaconda2/envs/py3/lib/python3.6/site-packages (from wmd)
Building wheels for collected packages: wmd
  Destination directory: /var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/tmpvcvwtjh8pip-wheel-
  Running command /Users/aloosley/anaconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/tmpvcvwtjh8pip-wheel- --python-tag cp36
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/wmd
  copying wmd/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/wmd
  running build_ext
  building 'libwmdrelax' extension
  creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/or-tools
  creating build/temp.macosx-10.7-x86_64-3.6/or-tools/src
  creating build/temp.macosx-10.7-x86_64-3.6/or-tools/src/graph
  creating build/temp.macosx-10.7-x86_64-3.6/or-tools/src/base
  creating build/temp.macosx-10.7-x86_64-3.6/or-tools/src/util
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/aloosley/anaconda2/envs/py3/include -arch x86_64 -I/Users/aloosley/anaconda2/envs/py3/include -arch x86_64 -I/Users/aloosley/anaconda2/envs/py3/lib/python3.6/site-packages/numpy/core/include -Ior-tools/src -I/Users/aloosley/anaconda2/envs/py3/include/python3.6m -c python.cc -o build/temp.macosx-10.7-x86_64-3.6/python.o -std=c++11 -march=native -ftree-vectorize -DNDEBUG -Wno-sign-compare -flto
  python.cc:6:10: fatal error: 'unordered_map' file not found
  #include <unordered_map>
           ^~~~~~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  Failed building wheel for wmd
  Running setup.py clean for wmd
  Running command /Users/aloosley/anaconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  removing 'build/temp.macosx-10.7-x86_64-3.6' (and everything under it)
  removing 'build/lib.macosx-10.7-x86_64-3.6' (and everything under it)
  'build/bdist.macosx-10.7-x86_64' does not exist -- can't clean it
  'build/scripts-3.6' does not exist -- can't clean it
  removing 'build'
Failed to build wmd
Installing collected packages: wmd
    Running command /Users/aloosley/anaconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-t86v0xhq-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/wmd
    copying wmd/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/wmd
    running build_ext
    building 'libwmdrelax' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/or-tools
    creating build/temp.macosx-10.7-x86_64-3.6/or-tools/src
    creating build/temp.macosx-10.7-x86_64-3.6/or-tools/src/graph
    creating build/temp.macosx-10.7-x86_64-3.6/or-tools/src/base
    creating build/temp.macosx-10.7-x86_64-3.6/or-tools/src/util
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/aloosley/anaconda2/envs/py3/include -arch x86_64 -I/Users/aloosley/anaconda2/envs/py3/include -arch x86_64 -I/Users/aloosley/anaconda2/envs/py3/lib/python3.6/site-packages/numpy/core/include -Ior-tools/src -I/Users/aloosley/anaconda2/envs/py3/include/python3.6m -c python.cc -o build/temp.macosx-10.7-x86_64-3.6/python.o -std=c++11 -march=native -ftree-vectorize -DNDEBUG -Wno-sign-compare -flto
    python.cc:6:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
Cleaning up...
  Removing source in /private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd
Command "/Users/aloosley/anaconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-t86v0xhq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd/
Exception information:
Traceback (most recent call last):
  File "/Users/aloosley/anaconda2/envs/py3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/aloosley/anaconda2/envs/py3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Users/aloosley/anaconda2/envs/py3/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Users/aloosley/anaconda2/envs/py3/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/Users/aloosley/anaconda2/envs/py3/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/Users/aloosley/anaconda2/envs/py3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-t86v0xhq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/gf/64v1_wtj6z1dd9xw6s83r73c0000gn/T/pip-build-glvr_lqt/wmd/
```

**Comment by vmarkovtsev** [comment]
@aloosley What's your GCC version? `gcc --version`

**Comment by aloosley** [comment]
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by vmarkovtsev** [comment]
According to https://stackoverflow.com/questions/26233011/what-could-cause-clang-to-not-find-the-unordered-map-header you should try to `export CXXFLAGS=-stdlib=libc++` before `pip install`

**Comment by aloosley** [comment]
@vmarkovtsev, The problem seems to be solved by explicitly installing conda compilers.

From one's root virtual environment (the following worked for me):
```
conda create -n yourvenvname python=3.6.4 clangxx_osx-64 clang_osx-64
source activate yourvenvname
pip install wmd
```

The second line also exports a lot of necessary env variables.

Hopefully this helps others (including @jmague).

**Comment by vmarkovtsev** [comment]
Nice find! Thanks for investigating.
